version: '3.3'

services:
  mist:
    image: r0gger/mistserver
    ports:
      - "554:554"
      - "1935:1935"
      - "4242:4242"
      - "8088:8080"
    restart: always
    networks:
      - traefik_webgateway
    volumes:
      - ./config:/config
      - ./media:/media
    tmpfs:
      - /dev/shm # To fix overflowing buffer. Now with "unlimited" size.
    labels:
         - "traefik.enable=true"
         - "traefik.docker.network=traefik_webgateway"
         # RTSP
         - "traefik.http.routers.mistrtsp.entrypoints=websecure"
         - "traefik.http.routers.mistrtsp.rule=Host(`mistrtsp.surrounded.space`)"
         - "traefik.http.routers.mistrtsp.tls.certresolver=default"
         - "traefik.http.routers.mistrtsp.service=mistrtsp-service"
         - "traefik.http.services.mistrtsp-service.loadbalancer.server.port=554"

         # RTMP
         - "traefik.http.routers.mistrtmp.entrypoints=websecure"
         - "traefik.http.routers.mistrtmp.rule=Host(`mistrtmp.surrounded.space`)"
         - "traefik.http.routers.mistrtmp.tls.certresolver=default"
         - "traefik.http.routers.mistrtmp.service=mistrtmp-service"
         - "traefik.http.services.mistrtmp-service.loadbalancer.server.port=1935"

         # WEB
         - "traefik.http.routers.mistweb.entrypoints=websecure"
         - "traefik.http.routers.mistweb.rule=Host(`mistweb.surrounded.space`)"
         - "traefik.http.routers.mistweb.tls.certresolver=default"
         - "traefik.http.routers.mistweb.service=mistweb-service"
         - "traefik.http.services.mistweb-service.loadbalancer.server.port=4242"

         # HTTP
         - "traefik.http.routers.mist.entrypoints=websecure"
         - "traefik.http.routers.mist.rule=Host(`mist.surrounded.space`)"
         - "traefik.http.routers.mist.tls.certresolver=default"
         - "traefik.http.routers.mist.service=mist-service"
         - "traefik.http.services.mist-service.loadbalancer.server.port=8080"

networks:
    traefik_webgateway:
      external:
        name: traefik_webgateway
