version: '3.3'

services:
  proxy:
    image: traefik:v2.2
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      # traefik-ception - or dashboard config
      #- "--api.dashboard=true"
      - "--api.insecure=true"
      # docker provider config
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # HTTP config
      - "--entrypoints.web.address=:80"
      # HTTPS TLS config
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.default.acme.httpchallenge=true"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
        #- "--certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.default.acme.email=email@email.com" # ADD EMAIL!
      - "--certificatesresolvers.default.acme.storage=/letsencrypt/acme.json"
    restart: always
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"

  #whoami:
    #image: "containous/whoami"
    #container_name: "simple-service"
    #labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.whoami.rule=Host(`whoami.surrounded.space`)"
      #- "traefik.http.routers.whoami.entrypoints=websecure"
      #- "traefik.http.routers.whoami.tls.certresolver=default"
    #networks:
      #- webgateway

networks:
  webgateway:
    driver: bridge
