version: '3'

services:
  proxy:
    image: traefik
    command: --web --docker --docker.domain=surrounded.space --docker.exposedbydefault=false --logLevel=DEBUG
    restart: always
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme/acme.json:/acme.json
    labels:
      - "traefik.backend=proxy"
      - "traefik.frontend.rule=Host:traefik.surrounded.space"
      - "traefik.port=8080"
      - "traefik.enable=true"  

networks:
  webgateway:
    driver: bridge
