version: '3'
services:
    hugo:
      image: jojomi/hugo:latest
      volumes:
        - ./src/:/src
        - ./output/:/output
      environment:
        - HUGO_REFRESH_TIME=3600
        - HUGO_THEME=hugo-classic
        - HUGO_BASEURL=http://blog.surrounded.space/
      restart: always

    hugo-caddy:
      container_name: "hugo-caddy"
      image: yobasystems/alpine-caddy
      restart: always
      ports:
        - 2015:2015
        #- 443:443
      volumes:
        - ./Caddyfile:/etc/Caddyfile
        - ./output:/var/www/html
        - ./.caddy:/root/.caddy
      networks: 
        - traefik_webgateway
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.hugo-caddy.entrypoints=websecure"
        - "traefik.http.routers.hugo-caddy.rule=Host(`blog.surrounded.space`)"
        - "traefik.http.routers.hugo-caddy.tls.certresolver=default"
        - "traefik.http.services.hugo-caddy.loadbalancer.server.port=2015"        

networks:
    traefik_webgateway:
      external:
        name: traefik_webgateway
