baseurl = "/"
languageCode = "en-us"
title = "surrounded.space Blog"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

#[[menu.main]]
#    name = "Home"
#    url = "/"
#    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A simple, minimal blog for those who love text."
    footer = "Jake | [Github](https://github.com/jakesmolka) | [Twitter](https://twitter.com/jakesmolka) | [Mail](mailto:jake.smolka ÄT mailbox DÖT org)"
